### ISSUE TITLE
Tail is not updated in real time / requires manual 'refresh' using Node >=10

### ISSUE THREAD

**Issue by meatwallace** [mixmaxhq/custody#82]
After upgrading to Node 10.16.x Custody does not seem to tail the log, only outputting the current state of the log when it's re-rendered. This effects both process logs and the 'main' combined log.

This can be reproduced by viewing a service's log (or the main log) and performing an action that causes the log to update. No update will be reflected, however simply pressing tab twice (swapping between process <-> main log) will update the log to reflect the expected state.

I was unable to install `@custody/cli` on Node 9.x, earlier versions of Node 10.x, and Node 12.x due to `node-gyp` issues with the `kexec` dependency, so I can't confirm when the issue was introduced. However, Custody works fine with Node 8.9.3.

I've tested this inside and outside of a tmux session in both Kitty and Mac's Terminal.app and been able to reliably reproduce it in all cases.

**Comment by meatwallace** [comment]
> I’m seeing that fs.watch doesn’t fire when I’m using Node 10 and touch files 

Thought I'd copy this here from Slack as a note if anyone else investigates.

**Comment by wearhere** [comment]
Ok, the issue here is that we use `node-tail` and in turn `fs.watch` to determine when log files have been updated, but `fs.watch` does not consistently emit `'change'` events on Node 10.16.0, possibly due to https://github.com/nodejs/node/issues/29460. `fs.watchFile` still works, but is less efficient per the docs, so I'll switch to that only if necessary and also suggest that users run custody under an older version of Node. Also filing a follow-up issue to track reverting this change.
